[workspace]
members = [
    "crates/seglog",
    "crates/tephra",
    "crates/tephra-client",
    "crates/tephra-proto",
    "crates/tephra-server",
    "crates/tephra-types",
    "site/tephra-site-examples",
]
resolver = "2"

[workspace.package]
repository = "https://github.com/tqwewe/tephra"

[workspace.dependencies]
# Internal crates
seglog = { path = "crates/seglog", version = "0.3.0" }
tephra = { path = "crates/tephra", version = "0.1.0" }
tephra-client = { path = "crates/tephra-client", version = "0.1.0" }
tephra-proto = { path = "crates/tephra-proto", version = "0.1.0" }
tephra-server = { path = "crates/tephra-server", version = "0.1.0" }
tephra-types = { path = "crates/tephra-types", version = "0.1.0" }

# Third-party
argh = "0.1"
config = { version = "0.15", default-features = false }
crc32fast = "1.5"
ctrlc = "3"
dashmap = "6"
flume = { version = "0.12", default-features = false }
fst = { version = "0.4.7", default-features = false }
nix = "0.31"
protobuf = "=4.35.1-release"
protobuf-codegen = "=4.35.1-release"
serde = "1"
smallvec = "1"
socket2 = "0.6.5"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = "0.3"

# Dev
criterion = "0.8"
tempfile = "3"
