[workspace]
members = [
    "crates/seglog",
    "crates/tephra",
    "crates/tephra-client",
    "crates/tephra-crashtest",
    "crates/tephra-proto",
    "crates/tephra-server",
    "crates/tephra-types",
    "site/tephra-site-examples",
]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"

[workspace.package]
repository = "https://github.com/tephradb/tephra"

[workspace.dependencies]
# Internal crates
seglog = { path = "crates/seglog", version = "0.3.5" }
tephra = { path = "crates/tephra", version = "0.3.5" }
tephra-client = { path = "crates/tephra-client", version = "0.5.0" }
tephra-proto = { path = "crates/tephra-proto", version = "0.2.0" }
tephra-server = { path = "crates/tephra-server", version = "0.4.0" }
tephra-types = { path = "crates/tephra-types", version = "0.1.4" }

# Third-party
argh = "0.1"
config = { version = "0.15", default-features = false }
crc32fast = "1.5"
ctrlc = { version = "3", features = ["termination"] }
dashmap = "6"
event-listener = { version = "5", default-features = false, features = ["std"] }
flume = { version = "0.12", default-features = false }
fst = { version = "0.4.7", default-features = false }
futures-core = "0.3"
nix = "0.31"
protobuf = "=4.35.1-release"
protobuf-codegen = "=4.35.1-release"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "logging"] }
rustls-native-certs = "0.8"
serde = "1"
sha2 = "0.10"
smallvec = "1"
socket2 = "0.6.5"
thiserror = "2"
tikv-jemalloc-ctl = "0.6"
tikv-jemallocator = "0.6"
tokio = { version = "1", default-features = false }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"

# Dev
criterion = "0.8"
rcgen = { version = "0.14", default-features = false, features = ["ring", "pem"] }
tempfile = "3"
