[package]
name = "tephra-proto"
description = "Wire protocol (protobuf messages + length-prefixed framing) shared by the tephra TCP server and client"
edition = "2024"
license = "Apache-2.0"
version = "0.1.0"

[dependencies]
tephra-types.workspace = true

protobuf.workspace = true

[build-dependencies]
protobuf-codegen.workspace = true
